"""Training utilities for ZipRerank."""

import math
import os

import torch
from accelerate.logging import get_logger
from PIL import Image
from torch import nn

from .loss import rank_net, soft_ranking_loss

logger = get_logger(__name__)


def resize_image_if_needed(img: Image.Image, max_size: int = 1024) -> Image.Image:
    """
    Resize image so that its largest dimension is at most max_size.
    
    This reduces the number of visual tokens generated by the vision encoder,
    significantly reducing memory usage during training and inference.
    
    Args:
        img: PIL Image to resize
        max_size: Maximum size for the largest dimension (default: 1024)
        
    Returns:
        Resized PIL Image (or original if already smaller)
    """
    width, height = img.size
    max_dim = max(width, height)
    
    if max_dim <= max_size:
        return img
    
    # Calculate new dimensions preserving aspect ratio
    scale = max_size / max_dim
    new_width = int(width * scale)
    new_height = int(height * scale)
    
    # Use LANCZOS for high-quality downsampling
    return img.resize((new_width, new_height), Image.LANCZOS)


def compute_generation_loss(model_outputs, labels, device):
    """Compute the loss for generation/language modeling task."""
    logits = model_outputs.logits[..., :-1, :].contiguous()
    labels = labels[..., 1:].contiguous()
    log_probs = -nn.functional.log_softmax(logits, dim=-1)

    if labels.dim() == log_probs.dim() - 1:
        labels = labels.unsqueeze(-1)

    epsilon = 0.0
    ignore_index = -100
    padding_mask = labels.eq(ignore_index)

    # Handle -100 indices
    labels = torch.clamp(labels, min=0)
    nll_loss = log_probs.gather(dim=-1, index=labels)
    smoothed_loss = log_probs.sum(dim=-1, keepdim=True, dtype=torch.float32)

    nll_loss.masked_fill_(padding_mask, 0.0)
    smoothed_loss.masked_fill_(padding_mask, 0.0)

    num_active_elements = padding_mask.numel() - padding_mask.long().sum()
    nll_loss = nll_loss.sum() / num_active_elements
    smoothed_loss = smoothed_loss.sum() / (num_active_elements * log_probs.shape[-1])

    loss = (1 - epsilon) * nll_loss + epsilon * smoothed_loss
    return loss, loss  # Return both total loss and generation loss


def compute_ranking_loss(
    model_outputs, rank_labels, source_lens, tokenizer, args, device, gt_indices=None
):
    """
    Compute the loss for ranking task.
    
    For Qwen3-VL with letter labels [A], [B], [C], etc.
    
    Args:
        model_outputs: Model forward outputs
        rank_labels: List of ranking labels per sample
        source_lens: Source lengths for each sample
        tokenizer: Tokenizer for encoding letters
        args: Training arguments
        device: Device to use
        gt_indices: Optional list of GT indices per sample (for soft_ranking loss)
    """
    # First extract scores for all samples
    all_scores = []
    
    for batch_index, true_rank in enumerate(rank_labels):
        pred_logits = model_outputs.logits[batch_index]
        # source_lens - 1 to get logits AFTER seeing full prompt
        rank_pred_index = source_lens[batch_index] - 1
        pred = pred_logits[rank_pred_index]

        # Extract logits for individual letter tokens: 'A', 'B', 'C', ...
        ALPH_START_IDX = ord('A')  # 65 - starting ASCII code for 'A'
        gather_indices = []
        for i in range(len(true_rank)):
            letter = chr(ALPH_START_IDX + i)
            tokens = tokenizer.encode(letter, add_special_tokens=False)
            if len(tokens) != 1:
                logger.warning(f"Letter '{letter}' tokenizes to {len(tokens)} tokens: {tokens}")
            gather_indices.append(tokens[0])
        scores = torch.gather(pred, 0, torch.tensor(gather_indices).to(device))
        all_scores.append(scores)
    
    # Handle soft_ranking loss (uses gt_indices)
    if args.ranking_loss == "soft_ranking":
        if gt_indices is None:
            # Fallback: assume position 0 in ranking is GT
            gt_indices = [[rank_labels[i][0]] for i in range(len(rank_labels))]
        
        # Stack scores for batched computation
        max_len = max(s.shape[0] for s in all_scores)
        padded_scores = []
        for s in all_scores:
            if s.shape[0] < max_len:
                pad = torch.full((max_len - s.shape[0],), float('-inf'), device=device)
                s = torch.cat([s, pad])
            padded_scores.append(s)
        scores_tensor = torch.stack(padded_scores, dim=0)  # [batch_size, max_candidates]
        
        decay = getattr(args, 'gt_position_decay', 0.5)
        rank_loss = soft_ranking_loss(
            scores_tensor, rank_labels, gt_indices,
            decay=decay
        )
        
        return rank_loss
    
    # RankNet loss computation
    rank_losses = torch.zeros(len(rank_labels))
    
    for batch_index, (true_rank, scores) in enumerate(zip(rank_labels, all_scores)):
        scores_sorted, _ = scores.sort(descending=True, dim=-1)
        true_scores = torch.gather(scores_sorted, 0, torch.tensor(true_rank).to(device))

        if args.ranking_loss == "ranknet":
            rank_losses[batch_index] = rank_net(
                scores.unsqueeze(0), true_scores.unsqueeze(0), weighted=args.weighted
            )

    rank_loss = rank_losses.mean().to(device)
    return rank_loss


def process_batch(batch, model, tokenizer, args, device, processor=None):
    """
    Process a single batch and compute the appropriate loss.
    
    For Qwen3-VL, images are handled by the processor and model natively.
    """
    # Initialize optional variables
    rank_labels = None
    source_lens = None
    gt_indices = None
    
    # Handle different batch structures
    if len(batch) == 5:
        # Combined objective with GT indices: (tokenized_input, label, rank_labels, source_lens, gt_indices)
        tokenized_input, label, rank_labels, source_lens, gt_indices = batch
    elif len(batch) == 4:
        # Combined objective (legacy): (tokenized_input, label, rank_labels, source_lens)
        tokenized_input, label, rank_labels, source_lens = batch
    elif len(batch) == 2:
        # Generation objective: (tokenized_input, label)
        tokenized_input, label = batch
    else:
        raise ValueError(f"Unexpected batch structure with {len(batch)} elements")
    
    # Move input tensors to device (preserve dict structure)
    model_inputs = {}
    if isinstance(tokenized_input, dict):
        for key, value in tokenized_input.items():
            if isinstance(value, torch.Tensor):
                model_inputs[key] = value.to(device)
            else:
                model_inputs[key] = value
    elif hasattr(tokenized_input, 'items'):
        # If it's a BatchEncoding, convert to dict
        for k, v in tokenized_input.items():
            model_inputs[k] = v.to(device) if isinstance(v, torch.Tensor) else v
    else:
        raise ValueError(f"Unexpected tokenized_input type: {type(tokenized_input)}")
    
    label = label.to(device)
    
    if args.objective == "generation" or args.objective == "combined":
        # Standard path: compute loss separately
        outputs = model(**model_inputs)
        loss, generate_loss = compute_generation_loss(outputs, label, device)
        
        if args.objective == "combined":
            # Compute ranking loss
            assert rank_labels is not None, "Rank labels are required for combined objective"
            
            rank_loss = compute_ranking_loss(
                outputs, rank_labels, source_lens, tokenizer, args, device, gt_indices
            )
            if not torch.isnan(rank_loss):
                if args.ranking_loss == "ranknet" and args.weighted:
                    loss = loss + torch.mul(rank_loss, 10.0)
                elif args.ranking_loss == "soft_ranking":
                    # Soft ranking: use configurable weight
                    gt_loss_weight = getattr(args, 'gt_loss_weight', 1.0)
                    loss = loss + torch.mul(rank_loss, gt_loss_weight)
                else:
                    loss = loss + rank_loss
            else:
                logger.warning(f"NaN detected in rank loss for batch, skipping loss addition")
        else:
            rank_loss = None
                
    else:  # pure ranking
        outputs = model(**model_inputs)
        loss = compute_ranking_loss(outputs, [label], [0], tokenizer, args, device, gt_indices)
        generate_loss = None
        rank_loss = loss

    return loss, generate_loss, rank_loss


def train_epoch(
    epoch,
    model,
    train_dataloader,
    optimizer,
    lr_scheduler,
    accelerator,
    args,
    tokenizer,
    processor=None,
    completed_steps=0,
):
    """
    Train for one epoch with comprehensive logging.
    
    Args:
        epoch: Current epoch number
        model: Qwen3-VL model
        train_dataloader: Training dataloader
        optimizer: Optimizer
        lr_scheduler: Learning rate scheduler
        accelerator: Accelerator for distributed training
        args: Training arguments
        tokenizer: Tokenizer
        processor: Qwen3-VL processor
        completed_steps: Number of steps already completed (for max_train_steps check)
        
    Returns:
        Tuple of (average loss for the epoch, number of steps completed)
    """
    import time
    
    model.train()
    total_loss = 0
    total_generate_loss = 0
    total_rank_loss = 0
    num_batches = len(train_dataloader)
    
    # For throughput calculation
    start_time = time.time()
    samples_processed = 0
    
    steps_in_epoch = 0  # Track optimizer steps completed in this epoch
    batch_loss_accum = 0.0
    batch_gen_loss_accum = 0.0
    batch_rank_loss_accum = 0.0
    
    for batch_idx, batch in enumerate(train_dataloader):
        step_start_time = time.time()
        
        # Use accelerator.accumulate() for proper gradient accumulation
        with accelerator.accumulate(model):
            # Process batch and compute loss
            loss, generate_loss, rank_loss = process_batch(
                batch, model, tokenizer, args, accelerator.device, processor
            )
            
            # Backward pass (Accelerate handles gradient accumulation)
            accelerator.backward(loss)
            
            # Accumulate losses for logging
            batch_loss_accum += loss.item()
            if generate_loss is not None:
                batch_gen_loss_accum += generate_loss.item()
            if rank_loss is not None:
                batch_rank_loss_accum += rank_loss.item()
            
            # Calculate gradient norm BEFORE optimizer.zero_grad() clears gradients
            total_norm = 0.0
            if hasattr(args, 'with_tracking') and args.with_tracking:
                for p in model.parameters():
                    if p.grad is not None:
                        param_norm = p.grad.data.norm(2)
                        total_norm += param_norm.item() ** 2
                total_norm = total_norm ** 0.5
            
            # Update parameters (only happens when gradients are synced)
            optimizer.step()
            lr_scheduler.step()
            optimizer.zero_grad()
        
        samples_processed += args.per_device_train_batch_size * accelerator.num_processes
        
        # Only count as a step when gradients are actually synced (optimizer step happens)
        if accelerator.sync_gradients:
            steps_in_epoch += 1
            global_step = completed_steps + steps_in_epoch
            
            # Check if we've reached max_train_steps
            if args.max_train_steps is not None and global_step >= args.max_train_steps:
                logger.info(f"Reached max_train_steps ({args.max_train_steps}) at step {steps_in_epoch} in epoch {epoch}")
                break
            
            # Calculate average loss over accumulated batches
            accum_steps = args.gradient_accumulation_steps
            avg_batch_loss = batch_loss_accum / accum_steps
            avg_batch_gen_loss = batch_gen_loss_accum / accum_steps
            avg_batch_rank_loss = batch_rank_loss_accum / accum_steps
            
            # Add to totals
            total_loss += avg_batch_loss
            if generate_loss is not None:
                total_generate_loss += avg_batch_gen_loss
            if rank_loss is not None:
                total_rank_loss += avg_batch_rank_loss
            
            # Reset accumulators
            batch_loss_accum = 0.0
            batch_gen_loss_accum = 0.0
            batch_rank_loss_accum = 0.0
            
            # Calculate step time and throughput
            step_time = time.time() - step_start_time
            
            # Detailed logging every 10 optimizer steps
            if steps_in_epoch % 10 == 0:
                current_lr = lr_scheduler.get_last_lr()[0]
                throughput = samples_processed / (time.time() - start_time)
                num_opt_steps = math.ceil(num_batches / args.gradient_accumulation_steps)
                
                logger.info(
                    f"Epoch {epoch} | Step {steps_in_epoch}/{num_opt_steps} | Global Step: {global_step}/{args.max_train_steps} | "
                    f"Loss: {avg_batch_loss:.4f} | "
                    f"Gen Loss: {avg_batch_gen_loss:.4f} | "
                    f"Rank Loss: {avg_batch_rank_loss:.4f} | "
                    f"LR: {current_lr:.2e} | "
                    f"Grad Norm: {total_norm:.4f} | "
                    f"Step Time: {step_time:.2f}s | "
                    f"Throughput: {throughput:.2f} samples/s"
                )
                
                # Log to WandB/tensorboard
                if hasattr(args, 'with_tracking') and args.with_tracking and accelerator.is_main_process:
                    log_dict = {
                        "train/loss": avg_batch_loss,
                        "train/learning_rate": current_lr,
                        "train/epoch": epoch,
                        "train/global_step": global_step,
                        "train/grad_norm": total_norm,
                        "train/step_time": step_time,
                        "train/throughput": throughput,
                    }
                    
                    if generate_loss is not None:
                        log_dict["train/generation_loss"] = avg_batch_gen_loss
                    if rank_loss is not None:
                        log_dict["train/ranking_loss"] = avg_batch_rank_loss
                    
                    # Log GPU memory if available
                    if torch.cuda.is_available():
                        for i in range(torch.cuda.device_count()):
                            log_dict[f"system/gpu_{i}_memory_allocated_gb"] = torch.cuda.memory_allocated(i) / 1024**3
                            log_dict[f"system/gpu_{i}_memory_reserved_gb"] = torch.cuda.memory_reserved(i) / 1024**3
                    
                    accelerator.log(log_dict, step=global_step)
            
            # Periodic evaluation and checkpoint saving
            eval_steps = getattr(args, 'eval_steps', 0)
            if eval_steps > 0 and global_step % eval_steps == 0 and accelerator.is_main_process:
                # Save checkpoint for evaluation
                checkpoint_dir = os.path.join(args.output_dir, "checkpoint-latest")
                logger.info(f"Saving checkpoint at step {global_step} for evaluation...")
                
                # Delete previous checkpoint if it exists
                import shutil
                if os.path.exists(checkpoint_dir):
                    try:
                        shutil.rmtree(checkpoint_dir)
                        logger.info(f"Deleted previous checkpoint to save disk space")
                    except Exception as e:
                        logger.warning(f"Failed to delete previous checkpoint: {e}")
                
                # Save model
                accelerator.wait_for_everyone()
                unwrapped_model = accelerator.unwrap_model(model)
                state_dict = accelerator.get_state_dict(model)
                unwrapped_model.save_pretrained(checkpoint_dir, state_dict=state_dict, safe_serialization=True)
                tokenizer.save_pretrained(checkpoint_dir)
                if processor is not None:
                    processor.save_pretrained(checkpoint_dir)
                logger.info(f"Checkpoint saved to {checkpoint_dir} (step {global_step})")
    
    # Calculate averages based on steps actually completed
    avg_loss = total_loss / steps_in_epoch if steps_in_epoch > 0 else 0
    avg_generate_loss = total_generate_loss / steps_in_epoch if steps_in_epoch > 0 else 0
    avg_rank_loss = total_rank_loss / steps_in_epoch if steps_in_epoch > 0 else 0
    
    logger.info(
        f"Epoch {epoch} completed | Steps: {steps_in_epoch} | "
        f"Avg Loss: {avg_loss:.4f} | "
        f"Avg Gen Loss: {avg_generate_loss:.4f} | "
        f"Avg Rank Loss: {avg_rank_loss:.4f}"
    )
    
    return avg_loss, steps_in_epoch


def save_checkpoint(model, tokenizer, processor, accelerator, output_dir):
    """Save model checkpoint (final model only, no optimizer state)."""
    accelerator.wait_for_everyone()
    
    # For DeepSpeed ZeRO-3, we need to gather the full state dict
    unwrapped_model = accelerator.unwrap_model(model)
    
    # Get the full state dict (handles DeepSpeed ZeRO sharding)
    state_dict = accelerator.get_state_dict(model)
    
    if accelerator.is_main_process:
        # Save the full model with gathered weights
        unwrapped_model.save_pretrained(
            output_dir,
            state_dict=state_dict,
            safe_serialization=True,
        )
        tokenizer.save_pretrained(output_dir)
        processor.save_pretrained(output_dir)
        logger.info(f"Checkpoint saved to {output_dir}")

